spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/movie_rental
    username: postgres
    password: postgres

  flyway:
    user: postgres
    password: postgres
    schemas: movie_rental
    locations: classpath:db/migration,./db.migration
